### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by p33k** [insolite/node-rcswitch2#1]
How do I install this and the rcswitch3 node and keep it updated without NPM?
Can you add a little install manual?

**Comment by slash-oleh** [comment]
I guess you mean installing it without npm registry but not avoiding of using npm at all? Then it is as simple as installing any package from alternate sources. For example you can use github link in your `package.json` and then just trigger `npm i`:
```json
"dependencies": {
    "rcswitch2": "https://github.com/insolite/node-rcswitch2/tarball/master"
}
```

**Comment by slash-oleh** [comment]
Actually for me there is a hope that changes made in this repo will eventually appear in original project. But as long as there is no positive or negative feedback yet from `node-rcswitch` maintainers, this project most likely will stay as an intermediate fork. That's why it's not on npm registry.

**Comment by p33k** [comment]
I get this errors when I try it that why (with an node-red install within iobroker)
```> rcswitch2@0.1.0 install /opt/iobroker/node_modules/iobroker.node-red/node_modules/rcswitch2

> node-gyp rebuild

make: Entering directory '/opt/iobroker/node_modules/iobroker.node-red/node_modules/rcswitch2/build'
  CXX(target) Release/obj.target/rcswitch/src/rcswitch.o
In file included from ../src/RCSwitchNode.h:6:0,
                 from ../src/rcswitch.cpp:2:
../src/../externals/rcswitch-pi/RCSwitch.h:43:26: fatal error: wiringPi.h: No such file or directory
     #include <wiringPi.h>
                          ^
compilation terminated.
rcswitch.target.mk:99: recipe for target 'Release/obj.target/rcswitch/src/rcswitch.o' failed
make: *** [Release/obj.target/rcswitch/src/rcswitch.o] Error 1
make: Leaving directory '/opt/iobroker/node_modules/iobroker.node-red/node_modules/rcswitch2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.34-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/iobroker.node-red/node_modules/rcswitch2
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rcswitch2@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rcswitch2@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-07T00_29_07_458Z-debug.log
```

**Comment by slash-oleh** [comment]
As mentioned in "Requirements" section you need the `wiringPi` library to be installed.

**Comment by p33k** [comment]
sorry I mixed up my installations because I startet over fresh 2 times with my PI. I forgot to install wiringPi this time...
